import { NgModule } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';
import { MatToolbarModule,
         MatIconModule,
         MatAutocompleteModule,
         MatDatepickerModule,
         MatInputModule,
         MatRadioModule,
         MatSelectModule,
         MatCheckboxModule,
         MatSliderModule,
         MatSlideToggleModule,
         MatMenuModule,
         MatSidenavModule,
         MatListModule,
         MatGridListModule,
         MatCardModule,
         MatTabsModule,
         MatButtonModule,
         MatButtonToggleModule,
         MatChipsModule,
         MatProgressSpinnerModule,
         MatProgressBarModule,
         MatDialogModule,
         MatTooltipModule,
         MatSnackBarModule,
         } from '@angular/material';

@NgModule({
  imports: [    // TODO: Move all MatModules to own barrel module
    FlexLayoutModule,
    MatToolbarModule,
    MatIconModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatInputModule,
    MatRadioModule,
    MatSelectModule,
    MatCheckboxModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatTabsModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
  ],
  exports: [
    FlexLayoutModule,
    MatToolbarModule,
    MatIconModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatInputModule,
    MatRadioModule,
    MatSelectModule,
    MatCheckboxModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatTabsModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
  ]
})

export class DesignModule { }
